language: minimal
install:
  - wget https://ziglang.org/builds/zig-linux-x86_64-0.3.0+5b3f7a8e.tar.xz
  - tar xf zig-linux-x86_64-0.3.0+5b3f7a8e.tar.xz
  - mv zig-linux-x86_64-0.3.0+5b3f7a8e bin
script:
  - ./bin/zig test src/all_test.zig